export const ADD_BURGER_STUFFING = "ADD_BURGER_STUFFING";
export const ADD_BURGER_BUN = "ADD_BURGER_BUN";
export const DELETE_BURGER_STUFFING = "DELETE_BURGER_STUFFING";
export const REPLACE_BURGER_STUFFING = "REPLCAE_BURGER_STUFFING";
